### ISSUE TITLE
BPF_MAP_COUNTER: panic: counter cannot decrease in goroutine 116 

### ISSUE THREAD

**Issue by andrea-tomassi** [solo-io/bumblebee#94]
Hi all, I have written several bpf programs running them with Bumblebee and I found his approach very simple. But now I'm stuck with a user-space code error and I can't figure out the problem origin.
Actually, the error is quite clear and well defined:

```

panic: counter cannot decrease in goroutine 116 [running]:                                                                                                                              
github.com/prometheus/client_golang/prometheus.(*counter).Add(0xc001ad8060, 0xc008000000000000)
github.com/solo-io/bumblebee/pkg/stats.(*setCounter).Set(0xc00269c7c0, {0xf320f0, 0xc001acf880}, 0xd, 0xc000ff8180)
github.com/solo-io/bumblebee/pkg/loader.(*loader).startHashMap(0xc000012270, {0xf320f0, 0xc001acf880}, 0xc00029d7c0, 0xc0000c5c20, {0xf22220, 0xc00269c7c0}, {0xc0001140e0, 0x1d}, {0xf32748, ...})
/home/runner/work/bumblebee/bumblebee/pkg/loader/loader.go:400 +0x843
github.com/solo-io/bumblebee/pkg/loader.(*loader).WatchMaps.func2()
/home/runner/work/bumblebee/bumblebee/pkg/loader/loader.go:286 +0x18c
golang.org/x/sync/errgroup.(*Group).Go.func1()
/home/runner/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0xb4
created by golang.org/x/sync/errgroup.(*Group).Go
/home/runner/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0xb3


```

This happens because the value for the counter map in my ebpf is going to decrease. Just to confirm the problem I moved the map to gauge and the error disappears.
I guess using a gauge is not the solution, in fact I'm expecting a monotonic data, because I just increment the counter by 1 for each ebpf event.
On the other hand, I cannot understand the origin of this kind of race condition, in fact the ebpf code contains a specific check on that:

```
// pointer_to_key is a pointer to a struct representing the object I'm tracking down by incrementing the counter. 
// the struct is allocated into a PER_CPU_ARRAY

u64 *cntp;	
cntp = bpf_map_lookup_elem(&my_bpf_hash_map_counter, pointer_to_key); // declared as SEC(".maps.counter");
if (cntp) 
{
	__sync_fetch_and_add(cntp, 1);
}

else 
{
	u64 cnt = 1;
	bpf_map_update_elem(&my_bpf_hash_map_counter, pointer_to_key, &cnt, BPF_NOEXIST);
}

```

I'm not an eBpf expert, however I cannot see how the counter value could be lower that the previous value here.
I think the bpf_map_update_elem function is the only one that could "decrease" some value. However both the if-else than the BPF_NOEXIST flag should be preventing from updating an higher existing record.
Any idea would be very apreciated!
Thanks!

[EDIT]

I have an update on that issue: the problem had nothing to do with concurrency.
After debugging a while, I've found that my_bpf_hash_map_t  keys content was wrong.
In fact I populated in a very bad way these keys, and happened that keys I was expecting as EQUALS were actually DIFFERENT for the bpf map. I know that thanks to the bpf_trace_printk, showing me the return value == 0 for
bpf_map_update_elem(&my_bpf_hash_map, pointer_to_key, &cnt, BPF_NOEXIST);
I guess something like that happened: immagine this is key A:
    char val_1 = ['f','o','o','\0' ..... (something more I ignore causing bpf consider this different)];
	...
	char val_6 = ['b','a','r','\0' ..... (something more I ignore causing bpf consider this different)];
	
	u32 number = 1234;
...and this is key B:
    char val_1 = ['f','o','o','\0' ..... (something more I ignore causing bpf consider this different)];
	...
	char val_6 = ['b','a','r','\0' ..... (something more I ignore causing bpf consider this different)];
	
	u32 number = 1234;
However, this still cannot explain the client code error. An so, this is what was going on on the (GOlang) user-space:
Keys equality was correctly detected by the user space code (while reading the copy of values from the same shared map), and so when a new ebpf key is created, the respective counter's value appears to be as a drop to the value of 1 (on the user-side point of view).
Writing good content into keys this behavior was solved and now ebpf maps creates a new key only if the content actually differs for meaningful differences.

**Comment by andrea-tomassi** [comment]
I'm adding some more details, I think this is somehow interesting:

I finally solved the issue, this is my final analysis with the fix that makes the code working just fine:
The problem was inside the key itself. It is a struct with char[] fields.
In fact the BPF_MAP_TYPE_HASH consider as unique key the whole char[] content, INCLUDING the part following the '\0' termination charcter (and this is just obvious, my fault).
On the other hand, the user-space program reads keys as String, so the meaningful part of the key is just the one before the '\0' character.
I use PER_CPU_ARRAY to store keys (to overcome the 512 bytes limit). So the actual memory area is initialized to 0, but it gets dirty after the first usage.
This causes that multiple keys with the same meaningful part of the string gives a clash of keys.
e.g.
key1[] {'f', 'o', 'o', '\0', 'Q', 'z', '3' .....}
key2[] {'f', 'o', 'o', '\0', 'F', '3', '?' .....}
The solution is initializing the whole char[] to all zeros all the time before updating the my_bpf_hash_map_counter
